### ISSUE TITLE
Can't open workflow tab

### ISSUE THREAD

**Issue by InsonusK** [Otanikotani/view-github-actions-idea-plugin#36]
I have closed workflow tab and can't find menu to open it again.

**Comment by InsonusK** [comment]
Workflow tab has opened by it self.

**Comment by Otanikotani** [comment]
Hmm, there was a way of calling an action like "View Workflows" from "Find Action..." menu, but apparently after update to 2020.1 that action is not available anymore. I will take a look

**Comment by ghost** [comment]
It did not open by default, need help on how should I Open it?
@Otanikotani

**Comment by thejamespower** [comment]
This is not working for me either on 2020.2.3. I have no 'Workflow' tab in the VCS window, nor do I have the 'Open workflow' action.

**Comment by RedNesto** [comment]
Version 1.1.8 was made before merging my PR so that's expected.
I compiled master myself and I noticed https://github.com/Otanikotani/view-github-actions-idea-plugin/commit/2690ea830ba2d2e2c2e652623f156edc54073729 breaks the plugin because of a binary incompatibility between the [IDE's kotlin version (1.3.72)](https://github.com/JetBrains/intellij-community/blob/d36d6c7ccdd6b4fe214fed47ccde955108d42aef/build/dependencies/gradle.properties#L3) and the one the plugin is built against (1.4.10)
<details>
<summary>Stacktrace for the curious</summary>

```
java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(java.lang.Class, java.lang.String, java.lang.String, int)'
	at org.github.otanikotani.workflow.GitHubWorkflowRunManager.<clinit>(GitHubWorkflowRunManager.kt)
	at org.github.otanikotani.workflow.GitHubWorkflowRunManager$RemoteUrlsListener.repositoryChanged(GitHubWorkflowRunManager.kt:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:636)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:380)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:366)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:32)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:180)
	at com.sun.proxy.$Proxy94.dirtyUnder(Unknown Source)
	at git4idea.annotate.GitRepositoryForAnnotationsListener$1.repositoryChanged(GitRepositoryForAnnotationsListener.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:636)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:384)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:366)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:32)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:187)
	at com.sun.proxy.$Proxy91.repositoryChanged(Unknown Source)
	at git4idea.repo.GitRepositoryManager.lambda$notifyListenersAsync$3(GitRepositoryManager.java:113)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:183)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

</details>

After setting it back to 1.3.72 the action is there and works correctly.
